Repository osu-cs493-sp19/final-project-do-it-later, pull requests merged in 2019-06, with the labels that each got.

#7 Update OpenAPI Swagger file to match schemas with MySQL init script
  README.md
  docs/openapi.yaml
Labels: priority/high

#11 Add CRUD functionality for Course's API endpoints
  api/courses.js
  api/index.js
  db-init/00-db-init.sql
  lib/auth.js
  lib/validation.js
  models/course.js
  server.js
Labels: Ready for Review, WIP, development, priority/high

#10 Users endpoints
  .eslintrc.json
  api/assignments.js
  api/index.js
  api/submissions.js
  api/users.js
  lib/auth.js
  models/user.js
Labels: development, priority/high

#13 Documentation update
  .gitattributes
  docs/openapi.yaml
Labels: priority/low

#15 Add running instruction to README
  README.md
Labels: enhancement, priority/medium

#14 Done with /courses API endpoints
  .gitignore
  api/courses.js
  api/users.js
  lib/auth.js
  models/course.js
  package-lock.json
  package.json
Labels: Ready for Review, priority/high

#8 Add API for assignments & submissions API and Rate Limiting feature
  README.md
  api/assignments.js
  api/courses.js
  api/index.js
  api/rate_limiting.js
  api/submissions.js
  api/users.js
  compose.sh
  db-init/mongodb/00-create-user.sh
  db-init/mysql/00-db-init.sql
  docker-compose.yml
  lib/mongo.js
  lib/validation.js
  models/assignment.js
  models/submission.js
  package.json
  server.js
Labels: Ready for Review, development, priority/high
